-- StyleSprint product catalog schema.
-- Run this in the Supabase SQL editor before importing the dataset.

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  catalog_id bigint,
  name text not null,
  image_url text not null,
  brand text not null default 'StyleSprint',
  category text,
  product_type text,
  price numeric(10, 2) not null default 49.99,
  description text,
  tryon_ready boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.products
  add column if not exists catalog_id bigint,
  add column if not exists brand text not null default 'StyleSprint',
  add column if not exists category text,
  add column if not exists product_type text,
  add column if not exists price numeric(10, 2) not null default 49.99,
  add column if not exists description text,
  add column if not exists tryon_ready boolean not null default true,
  add column if not exists created_at timestamptz not null default now();

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  image_url text not null,
  storage_path text not null,
  image_kind text not null default 'gallery',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists product_images_product_id_sort_idx
  on public.product_images(product_id, sort_order, id);

create index if not exists products_category_idx
  on public.products(category);

create index if not exists products_product_type_idx
  on public.products(product_type);

create index if not exists products_catalog_id_idx
  on public.products(catalog_id);

create unique index if not exists products_catalog_id_unique_idx
  on public.products(catalog_id);

create unique index if not exists product_images_product_storage_unique_idx
  on public.product_images(product_id, storage_path);

alter table public.products enable row level security;
alter table public.product_images enable row level security;

drop policy if exists "Products are publicly readable" on public.products;
create policy "Products are publicly readable"
  on public.products
  for select
  using (true);

drop policy if exists "Product images are publicly readable" on public.product_images;
create policy "Product images are publicly readable"
  on public.product_images
  for select
  using (true);

-- Optional: create a public bucket in Dashboard > Storage named:
-- products
--
-- For a student/demo app, keep the bucket public so Flutter can load images
-- directly through public URLs.
