// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYBiwiR7EFTNWLrIB_KHgQpKsDeXJPCFg',
    appId: '1:550254977862:web:ebb2c147f6fcc8411f3b47',
    messagingSenderId: '550254977862',
    projectId: 'fyp-stylesprint',
    authDomain: 'fyp-stylesprint.firebaseapp.com',
    storageBucket: 'fyp-stylesprint.firebasestorage.app',
    measurementId: 'G-PTQZFF09Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbNFeH6MDKay7thwMiAcKCvKaDX1LRvpk',
    appId: '1:550254977862:android:21f5f4be0bff03f81f3b47',
    messagingSenderId: '550254977862',
    projectId: 'fyp-stylesprint',
    storageBucket: 'fyp-stylesprint.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCT9l13rmGnGYvbycakzWPtmo6T8_EtBY',
    appId: '1:550254977862:ios:30ca5387dfba7aa71f3b47',
    messagingSenderId: '550254977862',
    projectId: 'fyp-stylesprint',
    storageBucket: 'fyp-stylesprint.firebasestorage.app',
    iosBundleId: 'com.example.fypApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCT9l13rmGnGYvbycakzWPtmo6T8_EtBY',
    appId: '1:550254977862:ios:30ca5387dfba7aa71f3b47',
    messagingSenderId: '550254977862',
    projectId: 'fyp-stylesprint',
    storageBucket: 'fyp-stylesprint.firebasestorage.app',
    iosBundleId: 'com.example.fypApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYBiwiR7EFTNWLrIB_KHgQpKsDeXJPCFg',
    appId: '1:550254977862:web:a0b583260e88f9c61f3b47',
    messagingSenderId: '550254977862',
    projectId: 'fyp-stylesprint',
    authDomain: 'fyp-stylesprint.firebaseapp.com',
    storageBucket: 'fyp-stylesprint.firebasestorage.app',
    measurementId: 'G-BVYNKTMK1L',
  );
}
